name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout file
      uses: moonrailgun/branch-filestorage-action@v1.2.2
      with:
        path: date
    - name: Read and show
      run: python monthly.py $(date) ${{ secrets.KEY}}

